---
kind: ReplicationController
apiVersion: v1
metadata:
  name: blue
  labels:
    app: blue
spec:
  replicas: 1
  selector:
    app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: blue
        image: irtaza06/linuxls:blue
        ports:
        - name: http-server
          containerPort: 80
