# Generated by Django 2.2.7 on 2019-11-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linuxls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='videoURL',
            field=models.URLField(max_length=300),
        ),
    ]
